---
# tasks file for compose

- name: install compose
  get_url:
    url: '{{ compose_binary }}'
    dest: /usr/local/bin/docker-compose
    mode: 0777

- name: install bash_completion
  get_url:
    url: '{{ bash_completition }}'
    dest: /etc/bash_completion.d/docker-compose
    mode: 0644